version: 1.0.{build}

image: Visual Studio 2017

before_build:
    - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"

build_script:
    - mkdir build
    - cd build
    - cmake .. -G "NMake Makefiles"
    - nmake
